smoke-test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,10 +4,11 @@ commands:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     steps:
       - run:
-          name: Destroy environments ${CIRCLE_WORKFLOW_ID:0:7}
+          name: Destroy environments
           when: on_fail
           command: |
             # Your code here
+            echo "Destroying environment: ${CIRCLE_WORKFLOW_ID:0:7}
             aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
             aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
             aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}    
@@ -354,9 +355,11 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
               # Change this to 0 after the job fails
-              echo "Frontend smoke test passed"
+              # echo "Frontend smoke test passed"
+              exit 1;
             else
-              echo "Frontend smoke test failed"
+              # echo "Frontend smoke test failed"
+              exit 1;
             fi
       # Here's where you will add some code to rollback on failure 
       - destroy-environment
